import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowUpRight, Bot, Box, CircleCheck, Clock3, CloudRain, Crosshair, Database, Flame, Menu, PackageCheck, Snowflake, Truck, X } from "lucide-react";
import { fleet360Api } from "./api/fleet360Api";
import { OperationsMap } from "./components/OperationsMap";
import { MetricCard } from "./components/MetricCard";
import { SectionHeader } from "./components/SectionHeader";
import type { DetailSelection, Disruption, Shipment, TemperatureLog, Vehicle, WeatherImpact } from "./types";

const formatDate = (value: string) => new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const formatValue = (value: number) => value >= 10000000 ? `₹${(value / 10000000).toFixed(1)} Cr` : `₹${(value / 100000).toFixed(1)} L`;
const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const impactRank = (value: string) => ({ LOW: 1, MEDIUM: 2, HIGH: 3, CRITICAL: 4 }[value.toUpperCase()] ?? 0);

function Badge({ children, tone = "neutral" }: { children: React.ReactNode; tone?: string }) {
  return <span className={`badge badge-${tone.toLowerCase()}`}>{children}</span>;
}

function App() {
  const [shipments, setShipments] = useState<Shipment[]>([]);
  const [fleet, setFleet] = useState<Vehicle[]>([]);
  const [idleFleet, setIdleFleet] = useState<Vehicle[]>([]);
  const [disruptions, setDisruptions] = useState<Disruption[]>([]);
  const [temperatures, setTemperatures] = useState<Record<string, TemperatureLog[]>>({});
  const [weatherImpacts, setWeatherImpacts] = useState<Record<string, WeatherImpact[]>>({});
  const [selection, setSelection] = useState<DetailSelection>(null);
  const [assistantMessage, setAssistantMessage] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    let active = true;
    Promise.all([fleet360Api.getHealth(), fleet360Api.getShipments(), fleet360Api.getFleet(), fleet360Api.getIdleFleet(), fleet360Api.getDisruptions()])
      .then(async ([, shipmentData, fleetData, idleData, disruptionData]) => {
        const coldEntries = await Promise.all(shipmentData.filter((shipment) => shipment.temperature_required).map(async (shipment) => [shipment.shipment_id, await fleet360Api.getTemperature(shipment.shipment_id)] as const));
        const weatherEntries = await Promise.all(disruptionData.map(async (disruption) => [disruption.disruption_id, await fleet360Api.getWeatherImpacts(disruption.disruption_id)] as const));
        if (!active) return;
        setShipments(shipmentData); setFleet(fleetData); setIdleFleet(idleData); setDisruptions(disruptionData); setTemperatures(Object.fromEntries(coldEntries)); setWeatherImpacts(Object.fromEntries(weatherEntries));
      })
      .catch(() => { if (active) setError(true); })
      .finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);

  const weatherImpactByShipment = useMemo(() => Object.values(weatherImpacts).flat().reduce<Record<string, WeatherImpact>>((result, impact) => {
    if (!result[impact.shipment_id] || impactRank(impact.impact_level) > impactRank(result[impact.shipment_id].impact_level)) result[impact.shipment_id] = impact;
    return result;
  }, {}), [weatherImpacts]);
  const coldAlerts = useMemo(() => Object.values(temperatures).filter((logs) => { const latest = logs.at(-1); return latest && (latest.temperature_c < latest.temperature_min || latest.temperature_c > latest.temperature_max); }).length, [temperatures]);
  const atRiskIds = useMemo(() => new Set(shipments.filter((shipment) => shipment.status === "delayed" || shipment.priority === "high" || shipment.priority === "critical").map((shipment) => shipment.shipment_id).concat(Object.keys(weatherImpactByShipment))), [shipments, weatherImpactByShipment]);
  const criticalIds = useMemo(() => new Set(shipments.filter((shipment) => shipment.priority === "critical").map((shipment) => shipment.shipment_id).concat(Object.values(weatherImpactByShipment).filter((impact) => impact.impact_level === "CRITICAL").map((impact) => impact.shipment_id))), [shipments, weatherImpactByShipment]);
  const attentionShipments = useMemo(() => shipments.filter((shipment) => atRiskIds.has(shipment.shipment_id)).sort((a, b) => {
    const aImpact = weatherImpactByShipment[a.shipment_id]; const bImpact = weatherImpactByShipment[b.shipment_id];
    return (bImpact ? impactRank(bImpact.impact_level) : impactRank(b.priority)) - (aImpact ? impactRank(aImpact.impact_level) : impactRank(a.priority));
  }), [shipments, atRiskIds, weatherImpactByShipment]);
  const selectedDisruptionId = selection?.kind === "disruption" ? selection.item.disruption_id : undefined;
  const selectedAffectedIds = selectedDisruptionId ? new Set((weatherImpacts[selectedDisruptionId] ?? []).map((impact) => impact.shipment_id)) : new Set<string>();

  if (loading) return <div className="app-loading"><div className="loading-mark">F</div><p>Connecting to Fleet 360 backend...</p></div>;
  return <div className="app-shell">
    <Header />
    <main className="dashboard">
      <div className="dashboard-heading"><div><span className="eyebrow">CONTROL ROOM / LIVE OPERATIONS</span><h1>From disruption signals to actionable decisions.</h1><p>Monitor active shipments, network disruptions, temperature excursions, and available fleet capacity.</p></div><div className="data-chip"><Database size={15} /> Synthetic operations dataset</div></div>
      {error && <div className="error-banner"><AlertTriangle size={18} /><div><strong>Unable to connect to Fleet 360 backend.</strong><span>Start the FastAPI service and refresh this dashboard.</span></div></div>}
      <section className="metric-grid"><MetricCard label="Active Shipments" value={shipments.length} tone="blue" icon={PackageCheck} /><MetricCard label="At Risk" value={atRiskIds.size} tone="orange" icon={AlertTriangle} /><MetricCard label="Critical" value={criticalIds.size} tone="red" icon={Flame} /><MetricCard label="Idle Fleet" value={idleFleet.length} tone="teal" icon={Truck} /><MetricCard label="Cold-Chain Alerts" value={coldAlerts} tone="slate" icon={Snowflake} /></section>
      <section className="map-section panel"><SectionHeader title="Operational Map" eyebrow="NETWORK AWARENESS" action={<div className="map-legend"><span><i className="legend-line" />Shipment routes</span><span><i className="legend-dot disruption-dot" />Disruptions</span><span><i className="legend-dot fleet-dot" />Idle fleet</span></div>} /><div className="map-frame"><OperationsMap shipments={shipments} disruptions={disruptions} idleFleet={idleFleet} selectedDisruptionId={selectedDisruptionId} affectedShipmentIds={selectedAffectedIds} /><div className="map-note"><Crosshair size={14} /> Approximate city-level positions from synthetic routes</div></div></section>
      <div className="content-grid"><DisruptionPanel disruptions={disruptions} impacts={weatherImpacts} onSelect={setSelection} /><PriorityPanel shipments={attentionShipments} impacts={weatherImpactByShipment} onSelect={setSelection} /></div>
      <div className="three-grid"><ColdChainPanel temperatures={temperatures} shipments={shipments} onSelect={setSelection} /><IdleFleetPanel fleet={idleFleet} /><section className="panel compact-panel response-panel"><SectionHeader title="Recommended Actions" eyebrow="RECOVERY WORKBENCH" action={<Clock3 size={17} className="section-icon" />} /><div className="empty-action"><div className="empty-icon"><CircleCheck size={20} /></div><strong>No automated recovery actions generated yet.</strong><p>Recovery recommendations will appear here as Fleet 360 intelligence agents process disruptions.</p></div></section></div>
      <Assistant message={assistantMessage} onAsk={() => setAssistantMessage("Operations Assistant is being connected to Fleet 360 intelligence.")} />
    </main>
    {selection && <DetailDrawer selection={selection} temperatures={temperatures[selection.kind === "shipment" ? selection.item.shipment_id : ""] ?? []} weatherImpacts={selection.kind === "shipment" ? [weatherImpactByShipment[selection.item.shipment_id]].filter((impact): impact is WeatherImpact => Boolean(impact)) : weatherImpacts[selection.item.disruption_id] ?? []} onClose={() => setSelection(null)} />}
  </div>;
}

function Header() { return <header className="topbar"><div className="brand"><div className="brand-mark">F<span>360</span></div><div><strong>Fleet 360</strong><span>Supply Chain Operations Assistant</span></div></div><div className="topbar-actions"><div className="system-status"><span className="status-dot" /> System Status <strong>Operational</strong></div><button className="icon-button" aria-label="Open navigation"><Menu size={19} /></button></div></header>; }
function DisruptionPanel({ disruptions, impacts, onSelect }: { disruptions: Disruption[]; impacts: Record<string, WeatherImpact[]>; onSelect: (selection: Exclude<DetailSelection, null>) => void }) { return <section className="panel disruptions-panel"><SectionHeader title="Active Disruptions" eyebrow={`${disruptions.length} ACTIVE SIGNALS`} /><div className="list-stack">{disruptions.map((disruption) => <button className="disruption-row" key={disruption.disruption_id} onClick={() => onSelect({ kind: "disruption", item: disruption })}><div className={`severity-indicator severity-${disruption.severity.toLowerCase()}`}><CloudRain size={17} /></div><div className="row-main"><strong>{disruption.title}</strong><span>{disruption.location} · {titleCase(disruption.type)}</span><small>{(impacts[disruption.disruption_id] ?? []).length} affected shipments · {disruption.expected_duration_hours}h estimated delay window</small></div><Badge tone={disruption.severity}>{disruption.severity}</Badge><ArrowUpRight size={16} className="row-arrow" /></button>)}</div></section>; }
function PriorityPanel({ shipments, impacts, onSelect }: { shipments: Shipment[]; impacts: Record<string, WeatherImpact>; onSelect: (selection: Exclude<DetailSelection, null>) => void }) { return <section className="panel priority-panel"><SectionHeader title="Priority Shipments" eyebrow="OPERATOR ATTENTION" /><div className="list-stack">{shipments.slice(0, 5).map((shipment) => { const impact = impacts[shipment.shipment_id]; return <button className="shipment-row" key={shipment.shipment_id} onClick={() => onSelect({ kind: "shipment", item: shipment })}><div className="shipment-icon"><Box size={17} /></div><div className="row-main"><strong>{shipment.shipment_id} <span className="cargo-label">{titleCase(shipment.cargo_type)}</span></strong><span>{shipment.origin} <b>→</b> {shipment.destination}</span><small>{impact ? impact.reason : `Due ${formatDate(shipment.deadline)} · ${formatValue(shipment.value)}`}</small></div><Badge tone={impact?.impact_level ?? shipment.priority}>{impact?.impact_level ?? shipment.priority}</Badge><ArrowUpRight size={16} className="row-arrow" /></button>; })}</div></section>; }
function ColdChainPanel({ temperatures, shipments, onSelect }: { temperatures: Record<string, TemperatureLog[]>; shipments: Shipment[]; onSelect: (selection: Exclude<DetailSelection, null>) => void }) { return <section className="panel compact-panel"><SectionHeader title="Cold-Chain Monitoring" eyebrow="TEMPERATURE CONTROL" action={<Snowflake size={17} className="section-icon" />} />{Object.entries(temperatures).slice(0, 3).map(([shipmentId, logs]) => { const latest = logs.at(-1); const excursion = latest && (latest.temperature_c < latest.temperature_min || latest.temperature_c > latest.temperature_max); const shipment = shipments.find((item) => item.shipment_id === shipmentId); return <button className="cold-row" key={shipmentId} onClick={() => shipment && onSelect({ kind: "shipment", item: shipment })}><div><strong>{shipmentId}</strong><span>{shipment?.cargo_type === "pharmaceuticals" ? "Pharmaceuticals" : "Temperature-controlled cargo"}</span></div><div className="temperature-trend">{logs.map((log) => <span key={log.log_id} className={log.temperature_c > log.temperature_max ? "temp-high" : ""}>{log.temperature_c.toFixed(1)}</span>)} <small>°C</small></div><Badge tone={excursion ? "high" : "ok"}>{excursion ? "Temperature Excursion" : "Within range"}</Badge></button>; })}{Object.keys(temperatures).length === 0 && <div className="empty-state">No temperature telemetry available.</div>}</section>; }
function IdleFleetPanel({ fleet }: { fleet: Vehicle[] }) { return <section className="panel compact-panel"><SectionHeader title="Idle Fleet" eyebrow="AVAILABLE CAPACITY" action={<Truck size={17} className="section-icon" />} />{fleet.map((vehicle) => <div className="fleet-row" key={vehicle.vehicle_id}><div className="fleet-avatar"><Truck size={16} /></div><div className="row-main"><strong>{vehicle.vehicle_id} <span>{vehicle.vehicle_type}</span></strong><span>{vehicle.current_location} · {vehicle.capacity.toLocaleString()} kg</span><small>Available {formatDate(vehicle.available_from)}</small></div>{vehicle.refrigerated && <Badge tone="teal">Refrigerated</Badge>}</div>)}<p className="panel-note">These assets may be available for redeployment.</p></section>; }
function Assistant({ message, onAsk }: { message: string; onAsk: () => void }) { const questions = ["What are the most critical shipments?", "Which shipments are affected by the Mumbai disruption?", "What should we do first?", "Which idle vehicle could be redeployed?"]; return <section className="assistant-panel"><div className="assistant-title"><div className="assistant-icon"><Bot size={19} /></div><div><span className="eyebrow">FUTURE INTELLIGENCE SURFACE</span><h2>Fleet 360 Assistant</h2></div><Badge tone="neutral">Coming next</Badge></div><p>The operations assistant will answer questions using Fleet 360 operational data. Intelligence connections are not enabled in this preview.</p><div className="suggestions">{questions.map((question) => <button key={question} onClick={onAsk}>{question}<ArrowUpRight size={14} /></button>)}</div>{message && <div className="assistant-message">{message}</div>}</section>; }
function DetailDrawer({ selection, temperatures, weatherImpacts, onClose }: { selection: Exclude<DetailSelection, null>; temperatures: TemperatureLog[]; weatherImpacts: WeatherImpact[]; onClose: () => void }) { const isShipment = selection.kind === "shipment"; return <div className="drawer-backdrop" onClick={onClose}><aside className="detail-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-header"><div><span className="eyebrow">{isShipment ? "SHIPMENT RECORD" : "DISRUPTION RECORD"}</span><h2>{isShipment ? selection.item.shipment_id : selection.item.title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close details"><X size={19} /></button></div>{isShipment ? <ShipmentDetails shipment={selection.item} temperatures={temperatures} /> : <DisruptionDetails disruption={selection.item} />}{<WeatherImpactBlock impacts={weatherImpacts} />}</aside></div>; }
function ShipmentDetails({ shipment, temperatures }: { shipment: Shipment; temperatures: TemperatureLog[] }) { return <><div className="drawer-status"><Badge tone={shipment.priority}>{shipment.priority} priority</Badge><Badge tone={shipment.status}>{titleCase(shipment.status)}</Badge></div><dl className="detail-list"><div><dt>Cargo</dt><dd>{titleCase(shipment.cargo_type)}</dd></div><div><dt>Lane</dt><dd>{shipment.origin} → {shipment.destination}</dd></div><div><dt>Current location</dt><dd>{shipment.current_location}</dd></div><div><dt>Deadline</dt><dd>{formatDate(shipment.deadline)}</dd></div><div><dt>Declared value</dt><dd>{formatValue(shipment.value)}</dd></div><div><dt>Carrier</dt><dd>{shipment.carrier}</dd></div></dl><div className="drawer-block"><span className="eyebrow">ROUTE WAYPOINTS</span><div className="route-pills">{shipment.route.map((point) => <span key={point}>{point}</span>)}</div></div>{temperatures.length > 0 && <div className="drawer-block"><span className="eyebrow">TEMPERATURE TELEMETRY</span><div className="drawer-temperature">{temperatures.map((log) => <span key={log.log_id} className={log.temperature_c > log.temperature_max ? "temp-high" : ""}>{log.temperature_c.toFixed(1)}°C</span>)}</div></div>}</>; }
function DisruptionDetails({ disruption }: { disruption: Disruption }) { return <><div className="drawer-status"><Badge tone={disruption.severity}>{disruption.severity}</Badge><Badge tone={disruption.status}>{disruption.status}</Badge></div><dl className="detail-list"><div><dt>Type</dt><dd>{titleCase(disruption.type)}</dd></div><div><dt>Location</dt><dd>{disruption.location}</dd></div><div><dt>Expected duration</dt><dd>{disruption.expected_duration_hours} hours</dd></div><div><dt>Observed</dt><dd>{formatDate(disruption.observed_at)}</dd></div></dl><div className="drawer-block"><span className="eyebrow">DESCRIPTION</span><p className="drawer-copy">{disruption.description}</p></div><div className="drawer-block"><span className="eyebrow">AFFECTED AREA / ROUTES</span><div className="route-pills">{disruption.affected_routes.map((route) => <span key={route}>{route}</span>)}</div></div></>; }
function WeatherImpactBlock({ impacts }: { impacts: WeatherImpact[] }) { if (impacts.length === 0) return <div className="weather-impact empty-impact"><span className="eyebrow">WEATHER IMPACT</span><strong>No active weather disruption affecting this shipment.</strong></div>; const counts = { critical: impacts.filter((item) => item.impact_level === "CRITICAL").length, high: impacts.filter((item) => item.impact_level === "HIGH").length, medium: impacts.filter((item) => item.impact_level === "MEDIUM").length }; const totalDelay = impacts.reduce((sum, item) => sum + item.estimated_delay_hours, 0); return <div className="weather-impact"><div className="weather-impact-heading"><span className="eyebrow">WEATHER IMPACT ANALYSIS</span><Badge tone={impacts.length === 1 ? impacts[0].impact_level : "high"}>{impacts.length === 1 ? impacts[0].impact_level : `${impacts.length} affected`}</Badge></div>{impacts.length > 1 && <div className="impact-summary"><strong>{impacts.length} shipments affected</strong><span>{counts.critical} Critical · {counts.high} High · {counts.medium} Medium</span><span>Estimated total delay: {totalDelay.toFixed(1)} hours</span></div>}{impacts.map((impact) => <div className="impact-record" key={`${impact.disruption_id}-${impact.shipment_id}`}><div className="impact-record-top"><strong>{impact.shipment_id}</strong><Badge tone={impact.impact_level}>{impact.impact_level}</Badge></div><dl className="impact-facts"><div><dt>Estimated delay</dt><dd>{impact.estimated_delay_hours} hours</dd></div><div><dt>Route affected</dt><dd>{impact.route_affected ? "Yes" : "No"}</dd></div><div><dt>Cargo sensitivity</dt><dd>{impact.cargo_sensitivity}</dd></div><div><dt>Deadline pressure</dt><dd>{impact.deadline_pressure}</dd></div></dl><p>{impact.reason}</p></div>)}</div>; }

export default App;
